#!/bin/bash

if [ ! -d bbv ]; then
  echo Run build from the cheri-mips-snapshot directory
  exit 1
fi

set -ex
make -C bbv
make BBV_DIR=`pwd`/bbv/src/bbv -C lib/sail
coqc -Q bbv/src/bbv bbv -Q lib/sail Sail mips_extras.v
coqc -Q bbv/src/bbv bbv -Q lib/sail Sail mips_types.v
coqc -Q bbv/src/bbv bbv -Q lib/sail Sail mips.v
coqc -Q bbv/src/bbv bbv -Q lib/sail Sail cheri_types.v
coqc -Q bbv/src/bbv bbv -Q lib/sail Sail cheri.v
coqc -Q bbv/src/bbv bbv -Q lib/sail Sail cheri128_types.v
coqc -Q bbv/src/bbv bbv -Q lib/sail Sail cheri128.v
